#!/usr/bin/env python

import os
import sys

#include "aux_listtags.py"
ltAuxFilename='aux_listtags.py'
exec(compile(open(ltAuxFilename).read(),ltAuxFilename,'exec'))

myTags=set()

l_dbg_forloop=False
# Remember, this script's filename is always sys.argv[0], so len(sys.argv) returns
# the number of arguments PLUS ONE (for the filename)
# So therefore "if len(sys.argv) < 2" means "If no arguments were passed"
if (len(sys.argv) < 2 or sys.argv[1] == '-a'):
    myTags=listAllTags()
else:
    for arg in sys.argv[1:len(sys.argv)]:
        tagsForArg=listAllTags(arg)

        if l_dbg_forloop or d_dbg_all or l_dbg_all: print(f"Going to add listAllTags({arg})={tagsForArg} to myTags");
        if tagsForArg != None: myTags |= tagsForArg;


print(f"{listTagNames(myTags)}")
